http:
  port: "8081"
  host: "0.0.0.0"
  
  netsuite:
    host: ""
    port: "443"
    readTimeout: "930000"
    bufferSize: "1024"
    connectionIdleTimeout: "30000"
    reconn:
      frequency: "10000"
      attempts: "3"


scheduler:
 initialState: "started"
      
# CRT Mapping

uomCode:
  "EA": "4"
  "YR": "4"
  "HRS": "20"

formType:
# TRANSACTION_SOURCE : PROJECT_TYPE : RETENTION_INVOICE : Form Internal ID : NS Field Value : Legacy Subscription Number ## fields seperated by : and lines seperated by |
  "CONTRACT INVOICES:Install:N:1:238:null|CONTRACT INVOICES:Install:Y:2:105:null|ORA_Subscriptions:null:null:3:105:null|CONTRACT INVOICES:Box Sales:N:4:238:null|CONTRACT INVOICES:Service:N:5:105:null|CONTRACT INVOICES:Internal Project:N:6:105:null|CONTRACT MIGRATION:null:null:8:105:null|CONTRACT MIGRATION:null:null:3:105:Not Null"


test: "![LQXFQluCIRVpxze+vRcGFA==]"
test2: "{vault}secret/data/path1"

